# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'githubApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for githubApp
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Alamofire'
  pod 'JGProgressHUD'
  pod 'Loaf'
  pod 'SDWebImage'
  pod 'Swinject'
  
end
